package main

import (
	"encoding/json"
	"strings"
	"testing"
)

func parse(t *testing.T, src string) map[string]any {
	t.Helper()
	dec := json.NewDecoder(strings.NewReader(src))
	dec.UseNumber()
	var root map[string]any
	if err := dec.Decode(&root); err != nil {
		t.Fatal(err)
	}
	return root
}

// 각 매핑 규칙을 관통하는 소형 스키마의 골든 테스트.
func TestGenerateGolden(t *testing.T) {
	root := parse(t, `{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"$id": "urn:test:v1",
		"type": "object",
		"properties": {
			"kind": {"$ref": "#/$defs/kind"},
			"count": {"$ref": "#/$defs/int64NonNeg"},
			"note": {"type": "string"},
			"payload": {"type": "object"},
			"tags": {"type": "array", "items": {"type": "string"}},
			"entries": {"type": "array", "items": {
				"type": "object",
				"properties": {"path": {"type": "string"}, "mode": {"enum": ["a", "b"]}},
				"required": ["path"],
				"additionalProperties": false
			}}
		},
		"required": ["kind", "count", "payload"],
		"additionalProperties": false,
		"$defs": {
			"protocolVersion": {"const": 1},
			"int64NonNeg": {"type": "integer", "minimum": 0, "maximum": 9223372036854775807},
			"kind": {"enum": ["x/start", "x/end"]},
			"verdictish": {
				"type": "object",
				"required": ["verdict"],
				"oneOf": [
					{"properties": {"verdict": {"const": "go"}, "why": {"type": "string"}}, "additionalProperties": false},
					{"properties": {"verdict": {"const": "halt"}, "why": {"type": "string", "minLength": 1}, "sub": {"$ref": "#/$defs/int64NonNeg"}}, "required": ["why"], "additionalProperties": false}
				]
			}
		}
	}`)
	src, emitted, err := Generate(root, "golden.schema.json", "Root")
	if err != nil {
		t.Fatal(err)
	}
	got := string(src)

	const want = `// Code generated by tools/schemagen from golden.schema.json; DO NOT EDIT.
// 생성물 — 손으로 수정 금지(CLAUDE.md). 진실은 contracts의 JSON Schema다.

package gen

import "encoding/json"

type Kind string

const (
	KindXStart Kind = "x/start"
	KindXEnd   Kind = "x/end"
)

const ProtocolVersion int64 = 1

type VerdictishVerdict string

const (
	VerdictishVerdictGo   VerdictishVerdict = "go"
	VerdictishVerdictHalt VerdictishVerdict = "halt"
)

type Verdictish struct {
	Sub     *int64            ` + "`json:\"sub,omitempty\"`" + `
	Verdict VerdictishVerdict ` + "`json:\"verdict\"`" + `
	Why     *string           ` + "`json:\"why,omitempty\"`" + `
}

type RootEntriesItemMode string

const (
	RootEntriesItemModeA RootEntriesItemMode = "a"
	RootEntriesItemModeB RootEntriesItemMode = "b"
)

type RootEntriesItem struct {
	Mode *RootEntriesItemMode ` + "`json:\"mode,omitempty\"`" + `
	Path string               ` + "`json:\"path\"`" + `
}

type Root struct {
	Count   int64             ` + "`json:\"count\"`" + `
	Entries []RootEntriesItem ` + "`json:\"entries,omitempty\"`" + `
	Kind    Kind              ` + "`json:\"kind\"`" + `
	Note    *string           ` + "`json:\"note,omitempty\"`" + `
	Payload json.RawMessage   ` + "`json:\"payload\"`" + `
	Tags    []string          ` + "`json:\"tags,omitempty\"`" + `
}
`
	if got != want {
		t.Errorf("골든 불일치.\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
	if len(emitted) == 0 {
		t.Error("방출 타입 목록이 비어 있음")
	}
}

// 결정성: 같은 입력의 반복 생성은 바이트 단위로 동일하다.
func TestGenerateDeterministic(t *testing.T) {
	const schema = `{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"type": "object",
		"properties": {"b": {"enum": ["1"]}, "a": {"enum": ["2"]}, "c": {"enum": ["3"]}},
		"additionalProperties": false,
		"$defs": {"z": {"enum": ["v"]}, "y": {"const": "w"}}
	}`
	var prev string
	for i := 0; i < 20; i++ {
		src, _, err := Generate(parse(t, schema), "d.schema.json", "D")
		if err != nil {
			t.Fatal(err)
		}
		if i > 0 && string(src) != prev {
			t.Fatal("반복 생성 결과가 다름 — 비결정적 출력")
		}
		prev = string(src)
	}
}

// fail-closed: 계약 밖 스키마는 전부 생성 실패해야 한다.
func TestGenerateFailClosed(t *testing.T) {
	const d = `"$schema": "https://json-schema.org/draft/2020-12/schema",`
	cases := []struct {
		name, schema, wantErr string
	}{
		{
			"서브셋 밖 키워드",
			`{` + d + `"type": "object", "properties": {"x": {"type": "string", "anyOf": []}}}`,
			"서브셋 밖 키워드",
		},
		{
			"if-then 키워드",
			`{` + d + `"type": "object", "if": {"type": "object"}}`,
			"서브셋 밖 키워드",
		},
		{
			"판별 const 없는 oneOf 분기",
			`{` + d + `"type": "object", "oneOf": [{"properties": {"k": {"enum": ["a", "b"]}}}]}`,
			"판별 필드 const 없는 분기",
		},
		{
			"additionalProperties true",
			`{` + d + `"type": "object", "properties": {"x": {"type": "object", "additionalProperties": true}}}`,
			"additionalProperties",
		},
		{
			"문서 밖 $ref",
			`{` + d + `"type": "object", "properties": {"x": {"$ref": "other.json#/$defs/y"}}}`,
			"#/$defs/",
		},
		{
			"type 배열",
			`{` + d + `"type": "object", "properties": {"x": {"type": ["string", "null"]}}}`,
			"단일 문자열만",
		},
		{
			"미해석 $ref",
			`{` + d + `"type": "object", "properties": {"x": {"$ref": "#/$defs/none"}}}`,
			"해석 불가 $ref",
		},

		// [H] 리뷰 재현 우회의 회귀 고정
		{
			"$schema 누락",
			`{"type": "object"}`,
			"루트 $schema는 정확히",
		},
		{
			"다른 draft",
			`{"$schema": "https://json-schema.org/draft/2019-09/schema", "type": "object"}`,
			"루트 $schema는 정확히",
		},
		{
			"빈 oneOf",
			`{` + d + `"type": "object", "oneOf": []}`,
			"비어 있지 않은 배열",
		},
		{
			"분기 간 판별 필드 불일치",
			`{` + d + `"type": "object", "required": ["kind", "other"], "oneOf": [
				{"properties": {"kind": {"const": "a"}}},
				{"properties": {"other": {"const": "b"}}}
			]}`,
			"판별 필드 불일치",
		},
		{
			"판별 const 값 중복",
			`{` + d + `"type": "object", "required": ["kind"], "oneOf": [
				{"properties": {"kind": {"const": "a"}}},
				{"properties": {"kind": {"const": "a"}}}
			]}`,
			"판별 const 값 중복",
		},
		{
			"분기당 판별 const 복수",
			`{` + d + `"type": "object", "required": ["kind"], "oneOf": [
				{"properties": {"kind": {"const": "a"}, "sub": {"const": "x"}}}
			]}`,
			"정확히 하나여야 함",
		},
		{
			"판별 필드 미required",
			`{` + d + `"type": "object", "oneOf": [
				{"properties": {"kind": {"const": "a"}}},
				{"properties": {"kind": {"const": "b"}}}
			]}`,
			"base required 또는 모든 분기에서 required",
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			_, _, err := Generate(parse(t, c.schema), "bad.schema.json", "Bad")
			if err == nil {
				t.Fatal("생성이 성공함 — fail-closed 위반")
			}
			if !strings.Contains(err.Error(), c.wantErr) {
				t.Errorf("오류 = %v, %q 포함 기대", err, c.wantErr)
			}
		})
	}
}

// 분기 간 같은 필드의 정의가 다르면(const 합집합도 아니면) 병합 불가로 실패한다.
func TestGenerateBranchConflict(t *testing.T) {
	root := parse(t, `{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"type": "object",
		"required": ["k"],
		"oneOf": [
			{"properties": {"k": {"const": "a"}, "x": {"type": "string"}}},
			{"properties": {"k": {"const": "b"}, "x": {"type": "integer"}}}
		]
	}`)
	_, _, err := Generate(root, "c.schema.json", "C")
	if err == nil || !strings.Contains(err.Error(), "분기 간 정의 불일치") {
		t.Errorf("병합 불가 오류 기대, got %v", err)
	}
}
